### ISSUE TITLE
influxdb_purge_peer_data

### ISSUE THREAD

**Issue by damstux** [rossmcdonald/influxdb#7]
In cluster mode, why do you use "influxdb_purge_peer_data: yes" ?

If I play the ansible script several times, all the data are deleted. If I set  "influxdb_purge_peer_data: yes", cluster is in wrong state.

Can you help / explain me ?

**Comment by rossmcdonald** [comment]
@damstux The reason I added that variable is so that meta-service data and WAL can be wiped when configuring and testing clusters. InfluxDB's current clustering configuration is very fragile at the moment, so in order to ensure there are no issues (typically caused by leftover data from the WAL) it will wipe everything for a clean start.

I mentioned this in the `/vars/main.yml` file here:

```
# Whether or not to purge peer data on each run (useful for cluster testing). NOTE: This will
# cause catastrophic data loss on an active cluster/instance, so use caution.
```

So it should only be used when creating a cluster for the first time. Once the cluster is created, though, you shouldn't be using it. The `cluster-test.yml` only uses it so that you can recreate clusters very easily, but I have gone ahead and removed it to avoid confusion.

Thanks for letting me know!
